#!/bin/sh
# a bit of explanation:
# since we start the script with python -c, sys.argv looks like:
# ['-c', $params], so replace the first item to reflect the scriptname
ver=`python -c 'import sys;print(sys.version[0])'`

if [ $ver -eq 2 ]; then
    PYTHON=python3 # use python3 if standard interpreter is python(2)
else
    # else, e.g. on arch, python3 is default interpreter
    PYTHON=python
fi

$PYTHON -c 'import sys;sys.argv[0]="matuc";import matuc' "$@"

